### ISSUE TITLE
No support for google cloud datastore despite being listed on NPM

### ISSUE THREAD

**Issue by actual-nsnow** [sebsylvester/botbuilder-storage#10]
I found this repository on NPM under [botbuilder-storage-google-cloud-datastore](https://www.npmjs.com/package/botbuilder-storage-google-cloud-datastore). However, there doesn't seem to be any support for google cloud datastore. I checked branches and everything in the `/src` dir, but didn't see anything related to GCP datastore. Thanks.

**Comment by sebsylvester** [comment]
I did not publish that package. It was forked and republished by someone else as botbuilder-storage-google-cloud-datastore without adding support for the google cloud datastore 🤷‍♂️. I am no longer involved in maintaining the repo, that's why I just archived it.
